import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/pretendard-variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const hack = localFont({
  src: [
    {
      path: "../fonts/hack-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/hack-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/hack-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/hack-bolditalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-hack",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} ${hack.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
